package cs301.up.edu.labyrinth.enums;

public enum Arrow {
    TOP_LEFT, TOP_MIDDLE, TOP_RIGHT,
    RIGHT_TOP, RIGHT_MIDDLE, RIGHT_BOTTOM,
    BOTTOM_RIGHT, BOTTOM_MIDDLE, BOTTOM_LEFT,
    LEFT_BOTTOM, LEFT_MIDDLE, LEFT_TOP,
    None
}
