package cs301.up.edu.enums;

public enum TreasureType {
    BAT, BOOK, BOW, CANDLES, CHEST, COINS, CROWN, DRAGON, FOX, GEM, GHOST, GOBLET, HELMET, KEYS,
    MAP, MOTH, MOUSE, OWL, RING, SHIELD, SKULL, SPIDER, SWORD, URN
}
